name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate Pattern Compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run pattern validation
        run: pnpm run validate:patterns
      - name: Check pattern annotations
        run: pnpm run validate:annotations

  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm run lint
      - name: Run TypeScript check
        run: pnpm run typecheck

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm run test:unit
      - name: Run integration tests
        run: pnpm run test:integration
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  e2e:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Run E2E tests
        run: pnpm run test:e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: packages/react-app/playwright-report/
          retention-days: 30

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [validate, lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build application
        run: pnpm run build
      - name: Run performance checks
        run: pnpm run perf:check
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: packages/react-app/dist/
          retention-days: 7

  # deploy:
  #   name: Deploy (Preview)
  #   if: github.event_name == 'pull_request'
  #   runs-on: ubuntu-latest
  #   needs: [build, e2e]
  #   environment:
  #     name: preview
  #     url: ${{ steps.deploy.outputs.preview-url }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build
  #         path: packages/react-app/dist
  #     - name: Deploy to preview
  #       id: deploy
  #       run: echo "Would deploy to preview environment"

  # deploy-production:
  #   name: Deploy (Production)
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   needs: [build, e2e]
  #   environment:
  #     name: production
  #     url: https://football-tickets.example.com
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build
  #         path: packages/react-app/dist
  #     - name: Deploy to production
  #       run: echo "Would deploy to production environment"
