name: Page Deploy

on:
  push:
    branches: [main]
    paths:
      - 'packages/page/**'
      - '.github/workflows/page-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/page
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/setup.yml
        with:
          filter-packages: '@zenreact/page'
          install-dependencies: true

      - name: Build Page
        run: pnpm --filter @zenreact/page build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: zenreact
          directory: packages/page/.vitepress/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
